version: "3"
services:
  app:
    build:
      context: docker
    volumes:
      - ".:/var/www/html"
    ports:
      - "8888:80"
    links:
      - db
  db:
    platform: linux/arm64/v8
    image: mysql:8
    ports:
      - "3366:3306"
    command:
      mysqld
      --character-set-server=UTF8MB4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES UTF8MB4;'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ftg